---
llm:
  openai:
    client:
      base_url: https://openrouter.ai/api/v1

    model_settings:
      model: gpt-4o-mini
      max_tokens: 450
      temperature: 0.25

  aws:
    client:
      service_name: bedrock-runtime
      region_name: eu-north-1

    model_settings:
      model_id: eu.anthropic.claude-3-7-sonnet-20250219-v1:0
      max_tokens: 500
      temperature: 0.2


web:
  frontend:
    backend_host: http://127.0.0.1:8000 # To which backend host front calling - default uvicorn host:port 
    max_buffer: 6 # The maximum length of stored messages in chat history
    hold_after_summarization: 4 # How many last messages hold after summarization

logger:
  level: 
    global: DEBUG # Filter before files and console level
    files: INFO # or DEBUG
    console: DEBUG